set(LIBZXING_FILES
    core/src/bigint/BigInteger.cc
    core/src/bigint/BigInteger.cc
    core/src/bigint/BigInteger.hh
    core/src/bigint/BigInteger.hh
    core/src/bigint/BigIntegerAlgorithms.cc
    core/src/bigint/BigIntegerAlgorithms.cc
    core/src/bigint/BigIntegerAlgorithms.hh
    core/src/bigint/BigIntegerAlgorithms.hh
    core/src/bigint/BigIntegerLibrary.hh
    core/src/bigint/BigIntegerLibrary.hh
    core/src/bigint/BigIntegerUtils.cc
    core/src/bigint/BigIntegerUtils.cc
    core/src/bigint/BigIntegerUtils.hh
    core/src/bigint/BigIntegerUtils.hh
    core/src/bigint/BigUnsigned.cc
    core/src/bigint/BigUnsigned.cc
    core/src/bigint/BigUnsigned.hh
    core/src/bigint/BigUnsigned.hh
    core/src/bigint/BigUnsignedInABase.cc
    core/src/bigint/BigUnsignedInABase.cc
    core/src/bigint/BigUnsignedInABase.hh
    core/src/bigint/BigUnsignedInABase.hh
    core/src/bigint/NumberlikeArray.hh
    core/src/bigint/NumberlikeArray.hh
    core/src/zxing/aztec/AztecDetectorResult.cpp
    core/src/zxing/aztec/AztecDetectorResult.h
    core/src/zxing/aztec/AztecReader.cpp
    core/src/zxing/aztec/AztecReader.h
    core/src/zxing/aztec/decoder/Decoder.cpp
    core/src/zxing/aztec/decoder/Decoder.h
    core/src/zxing/aztec/detector/Detector.cpp
    core/src/zxing/aztec/detector/Detector.h
    core/src/zxing/BarcodeFormat.cpp
    core/src/zxing/BarcodeFormat.h
    core/src/zxing/Binarizer.cpp
    core/src/zxing/Binarizer.h
    core/src/zxing/BinaryBitmap.cpp
    core/src/zxing/BinaryBitmap.h
    core/src/zxing/ChecksumException.cpp
    core/src/zxing/ChecksumException.h
    core/src/zxing/common/Array.h
    core/src/zxing/common/BitArray.cpp
    core/src/zxing/common/BitArray.h
    core/src/zxing/common/BitArrayIO.cpp
    core/src/zxing/common/BitMatrix.cpp
    core/src/zxing/common/BitMatrix.h
    core/src/zxing/common/BitSource.cpp
    core/src/zxing/common/BitSource.h
    core/src/zxing/common/CharacterSetECI.cpp
    core/src/zxing/common/CharacterSetECI.h
    core/src/zxing/common/Counted.h
    core/src/zxing/common/DecoderResult.cpp
    core/src/zxing/common/DecoderResult.h
    core/src/zxing/common/detector/JavaMath.h
    core/src/zxing/common/detector/MathUtils.h
    core/src/zxing/common/detector/MonochromeRectangleDetector.cpp
    core/src/zxing/common/detector/MonochromeRectangleDetector.h
    core/src/zxing/common/detector/WhiteRectangleDetector.cpp
    core/src/zxing/common/detector/WhiteRectangleDetector.h
    core/src/zxing/common/DetectorResult.cpp
    core/src/zxing/common/DetectorResult.h
    core/src/zxing/common/GlobalHistogramBinarizer.cpp
    core/src/zxing/common/GlobalHistogramBinarizer.h
    core/src/zxing/common/GreyscaleLuminanceSource.cpp
    core/src/zxing/common/GreyscaleLuminanceSource.h
    core/src/zxing/common/GreyscaleRotatedLuminanceSource.cpp
    core/src/zxing/common/GreyscaleRotatedLuminanceSource.h
    core/src/zxing/common/GridSampler.cpp
    core/src/zxing/common/GridSampler.h
    core/src/zxing/common/HybridBinarizer.cpp
    core/src/zxing/common/HybridBinarizer.h
    core/src/zxing/common/IllegalArgumentException.cpp
    core/src/zxing/common/IllegalArgumentException.h
    core/src/zxing/common/PerspectiveTransform.cpp
    core/src/zxing/common/PerspectiveTransform.h
    core/src/zxing/common/Point.h
    core/src/zxing/common/reedsolomon/GenericGF.cpp
    core/src/zxing/common/reedsolomon/GenericGF.h
    core/src/zxing/common/reedsolomon/GenericGFPoly.cpp
    core/src/zxing/common/reedsolomon/GenericGFPoly.h
    core/src/zxing/common/reedsolomon/ReedSolomonDecoder.cpp
    core/src/zxing/common/reedsolomon/ReedSolomonDecoder.h
    core/src/zxing/common/reedsolomon/ReedSolomonException.cpp
    core/src/zxing/common/reedsolomon/ReedSolomonException.h
    core/src/zxing/common/Str.cpp
    core/src/zxing/common/Str.h
    core/src/zxing/common/StringUtils.cpp
    core/src/zxing/common/StringUtils.h
    core/src/zxing/datamatrix/DataMatrixReader.cpp
    core/src/zxing/datamatrix/DataMatrixReader.h
    core/src/zxing/datamatrix/decoder/BitMatrixParser.cpp
    core/src/zxing/datamatrix/decoder/BitMatrixParser.h
    core/src/zxing/datamatrix/decoder/DataBlock.cpp
    core/src/zxing/datamatrix/decoder/DataBlock.h
    core/src/zxing/datamatrix/decoder/DecodedBitStreamParser.cpp
    core/src/zxing/datamatrix/decoder/DecodedBitStreamParser.h
    core/src/zxing/datamatrix/decoder/Decoder.cpp
    core/src/zxing/datamatrix/decoder/Decoder.h
    core/src/zxing/datamatrix/detector/CornerPoint.cpp
    core/src/zxing/datamatrix/detector/CornerPoint.h
    core/src/zxing/datamatrix/detector/Detector.cpp
    core/src/zxing/datamatrix/detector/Detector.h
    core/src/zxing/datamatrix/detector/DetectorException.cpp
    core/src/zxing/datamatrix/detector/DetectorException.h
    core/src/zxing/datamatrix/Version.cpp
    core/src/zxing/datamatrix/Version.h
    core/src/zxing/DecodeHints.cpp
    core/src/zxing/DecodeHints.h
    core/src/zxing/Exception.cpp
    core/src/zxing/Exception.h
    core/src/zxing/FormatException.cpp
    core/src/zxing/FormatException.h
    core/src/zxing/IllegalStateException.h
    core/src/zxing/InvertedLuminanceSource.cpp
    core/src/zxing/InvertedLuminanceSource.h
    core/src/zxing/LuminanceSource.cpp
    core/src/zxing/LuminanceSource.h
    core/src/zxing/multi/ByQuadrantReader.cpp
    core/src/zxing/multi/ByQuadrantReader.h
    core/src/zxing/multi/GenericMultipleBarcodeReader.cpp
    core/src/zxing/multi/GenericMultipleBarcodeReader.h
    core/src/zxing/multi/MultipleBarcodeReader.cpp
    core/src/zxing/multi/MultipleBarcodeReader.h
    core/src/zxing/multi/qrcode/detector/MultiDetector.cpp
    core/src/zxing/multi/qrcode/detector/MultiDetector.h
    core/src/zxing/multi/qrcode/detector/MultiFinderPatternFinder.cpp
    core/src/zxing/multi/qrcode/detector/MultiFinderPatternFinder.h
    core/src/zxing/multi/qrcode/QRCodeMultiReader.cpp
    core/src/zxing/multi/qrcode/QRCodeMultiReader.h
    core/src/zxing/MultiFormatReader.cpp
    core/src/zxing/MultiFormatReader.h
    core/src/zxing/NotFoundException.h
    core/src/zxing/oned/CodaBarReader.cpp
    core/src/zxing/oned/CodaBarReader.h
    core/src/zxing/oned/Code128Reader.cpp
    core/src/zxing/oned/Code128Reader.h
    core/src/zxing/oned/Code39Reader.cpp
    core/src/zxing/oned/Code39Reader.h
    core/src/zxing/oned/Code93Reader.cpp
    core/src/zxing/oned/Code93Reader.h
    core/src/zxing/oned/EAN13Reader.cpp
    core/src/zxing/oned/EAN13Reader.h
    core/src/zxing/oned/EAN8Reader.cpp
    core/src/zxing/oned/EAN8Reader.h
    core/src/zxing/oned/ITFReader.cpp
    core/src/zxing/oned/ITFReader.h
    core/src/zxing/oned/MultiFormatOneDReader.cpp
    core/src/zxing/oned/MultiFormatOneDReader.h
    core/src/zxing/oned/MultiFormatUPCEANReader.cpp
    core/src/zxing/oned/MultiFormatUPCEANReader.h
    core/src/zxing/oned/OneDReader.cpp
    core/src/zxing/oned/OneDReader.h
    core/src/zxing/oned/OneDResultPoint.cpp
    core/src/zxing/oned/OneDResultPoint.h
    core/src/zxing/oned/UPCAReader.cpp
    core/src/zxing/oned/UPCAReader.h
    core/src/zxing/oned/UPCEANReader.cpp
    core/src/zxing/oned/UPCEANReader.h
    core/src/zxing/oned/UPCEReader.cpp
    core/src/zxing/oned/UPCEReader.h
    core/src/zxing/pdf417/decoder/BitMatrixParser.cpp
    core/src/zxing/pdf417/decoder/BitMatrixParser.h
    core/src/zxing/pdf417/decoder/DecodedBitStreamParser.cpp
    core/src/zxing/pdf417/decoder/DecodedBitStreamParser.h
    core/src/zxing/pdf417/decoder/Decoder.cpp
    core/src/zxing/pdf417/decoder/Decoder.h
    core/src/zxing/pdf417/decoder/ec/ErrorCorrection.cpp
    core/src/zxing/pdf417/decoder/ec/ErrorCorrection.h
    core/src/zxing/pdf417/decoder/ec/ModulusGF.cpp
    core/src/zxing/pdf417/decoder/ec/ModulusGF.h
    core/src/zxing/pdf417/decoder/ec/ModulusPoly.cpp
    core/src/zxing/pdf417/decoder/ec/ModulusPoly.h
    core/src/zxing/pdf417/detector/Detector.cpp
    core/src/zxing/pdf417/detector/Detector.h
    core/src/zxing/pdf417/detector/LinesSampler.cpp
    core/src/zxing/pdf417/detector/LinesSampler.h
    core/src/zxing/pdf417/PDF417Reader.cpp
    core/src/zxing/pdf417/PDF417Reader.h
    core/src/zxing/qrcode/decoder/BitMatrixParser.cpp
    core/src/zxing/qrcode/decoder/BitMatrixParser.h
    core/src/zxing/qrcode/decoder/DataBlock.cpp
    core/src/zxing/qrcode/decoder/DataBlock.h
    core/src/zxing/qrcode/decoder/DataMask.cpp
    core/src/zxing/qrcode/decoder/DataMask.h
    core/src/zxing/qrcode/decoder/DecodedBitStreamParser.cpp
    core/src/zxing/qrcode/decoder/DecodedBitStreamParser.h
    core/src/zxing/qrcode/decoder/Decoder.cpp
    core/src/zxing/qrcode/decoder/Decoder.h
    core/src/zxing/qrcode/decoder/Mode.cpp
    core/src/zxing/qrcode/decoder/Mode.h
    core/src/zxing/qrcode/detector/AlignmentPattern.cpp
    core/src/zxing/qrcode/detector/AlignmentPattern.h
    core/src/zxing/qrcode/detector/AlignmentPatternFinder.cpp
    core/src/zxing/qrcode/detector/AlignmentPatternFinder.h
    core/src/zxing/qrcode/detector/Detector.cpp
    core/src/zxing/qrcode/detector/Detector.h
    core/src/zxing/qrcode/detector/FinderPattern.cpp
    core/src/zxing/qrcode/detector/FinderPattern.h
    core/src/zxing/qrcode/detector/FinderPatternFinder.cpp
    core/src/zxing/qrcode/detector/FinderPatternFinder.h
    core/src/zxing/qrcode/detector/FinderPatternInfo.cpp
    core/src/zxing/qrcode/detector/FinderPatternInfo.h
    core/src/zxing/qrcode/ErrorCorrectionLevel.cpp
    core/src/zxing/qrcode/ErrorCorrectionLevel.h
    core/src/zxing/qrcode/FormatInformation.cpp
    core/src/zxing/qrcode/FormatInformation.h
    core/src/zxing/qrcode/QRCodeReader.cpp
    core/src/zxing/qrcode/QRCodeReader.h
    core/src/zxing/qrcode/Version.cpp
    core/src/zxing/qrcode/Version.h
    core/src/zxing/Reader.cpp
    core/src/zxing/Reader.h
    core/src/zxing/ReaderException.h
    core/src/zxing/ResultQR.cpp
    core/src/zxing/ResultQR.h
    core/src/zxing/Result.cpp
    core/src/zxing/Result.h
    core/src/zxing/ResultIO.cpp
    core/src/zxing/ResultPoint.cpp
    core/src/zxing/ResultPoint.h
    core/src/zxing/ResultPointCallback.cpp
    core/src/zxing/ResultPointCallback.h
    core/src/zxing/ZXing.h
)

if(WIN32)
    list(APPEND LIBZXING_FILES
        #core/src/win32/zxing/iconv.h
        #core/src/win32/zxing/stdint.h
        #core/src/win32/zxing/win_iconv.c
    )
endif()
